@baseUrl = http://localhost:3333


# @name Create_User
post {{baseUrl}}/users/ HTTP/1.1
Content-Type: application/json

{
    "name": "Marcon",
    "email": "marconc@mh4sh.dev",
    "password": "12345"
}
